name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size="2g"
          --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean test -DuseGrid=true -DgridUrl=http://localhost:4444/wd/hub
      
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          reports
        retention-days: 30

    - name: Upload to Backblaze B2
      if: always()
      run: |
        export AWS_S3_DISABLE_CHECKSUM_VALIDATION=true
        aws s3 cp reports s3://${{ secrets.B2_BUCKET_NAME }}/test-reports/ --recursive --endpoint-url https://${{ secrets.B2_ENDPOINT }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APPLICATION_KEY }}
